### ISSUE TITLE
Problem with schema_migrations table after 100 migrations.

### ISSUE THREAD

**Issue by ViktorNazarenko-ST** [PNixx/clickhouse-activerecord#75]
Current schema_migrations table structure is:
```
CREATE TABLE schema_migrations
(
    `version` String,
    `active` Int8 DEFAULT 1,
    `ver` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(ver)
PARTITION BY version
ORDER BY version
SETTINGS index_granularity = 8192;
```
So it will create 1 partition for each version. Default value for max_partitions_per_insert_block is 100, and actually it's bad to have too many partitions, so it's better to remove `PARTITION BY` from `schema_migrations` table definition.

Other wise if you have more then 100 migrations and try to do `db:structure:load`
You will got:
```
ActiveRecord::ActiveRecordError: Response code: 500:
Code: 252. DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc). 
```

**Comment by PNixx** [comment]
max_partitions_per_insert_block property was set in version 0.5.9

**Comment by ViktorNazarenko-ST** [comment]
I don't want to change that setting for clickhouse server, i just want `schema_migrations` do not have `PARTITION by version` it actually do not have sense.

**Comment by davidbodow-st** [comment]
`schema_migrations` is always going to be a very small table, so partitioning it is excessively complex / can lead to errors with default settings as shown above.

Instead, the default schema should omit the `PARTITION BY` clause because it will have no effect (or possibly even a negligible positive effect) on the types of queries that run against `schema_migrations` and, more importantly, it will save `clickhouse-activerecord` users needless configuration errors with some settings (such as in @ViktorNazarenko-ST 's initial message), thus making the gem simpler and less error prone.

@PNixx - would you be open to considering a PR implementing this change?

**Comment by davidbodow-st** [comment]
(If you strongly prefer the `PARTITION BY` clause, it would be better to partition by the month or year of the `ver` timestamp instead of the `version` string, which will lead to 1 part for each record)

**Comment by ViktorNazarenko-ST** [comment]
I've created PR #76  to remove `PARTITION BY`

**Comment by ViktorNazarenko-ST** [comment]
My PR merge, issue will be fixed in new version
